const { Router } = require('express');
const c = require('./account.controller');
const s = require('./account.schemas');
const { validate } = require('../../middleware/validate');
const { authenticate } = require('../../middleware/auth');
const { asyncHandler } = require('../../utils/asyncHandler');
const r = Router();
r.put('/location', authenticate, validate({ body: s.locationSchema }), asyncHandler(c.saveLocation));
r.get('/locations', authenticate, asyncHandler(c.locations));
r.post('/locations', authenticate, validate({ body: s.savedLocationSchema }), asyncHandler(c.addLocation));
r.delete('/locations/:id', authenticate, asyncHandler(c.removeLocation));
r.patch('/locations/:id/default', authenticate, asyncHandler(c.setDefaultLocation));
r.get('/wishlists', authenticate, asyncHandler(c.wishlists));
r.post('/wishlists', authenticate, validate({ body: s.wishlistCreate }), asyncHandler(c.createWishlist));
r.post('/wishlists/:index/items', authenticate, validate({ body: s.wishlistItem }), asyncHandler(c.toggleItem));
module.exports = r;
